format = """
[](#2b2d30)\
$username\
$hostname\
$sudo\
[](fg:#2b2d30 bg:#57c7fe)\
$directory\
[](fg:#57c7fe bg:#00ffa5)\
$nodejs\
$rust\
[](fg:#00ffa5 bg:#f3f99c)\
$git_branch\
$git_status\
[ ](fg:#f3f99c)\
"""

# nice dark blug bg color: bg:#33658A

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#2b2d30"
style_root = "fg:#ff5b56 bg:#2b2d30"
format = '[$user ]($style)'

[hostname]
trim_at = ""
style = "bg:#2b2d30"
format = '[(@$hostname)]($style)'

[sudo]
disabled = false
style = "bg:#2d2d30"
format = '[$symbol]($style)'

[directory]
style = "fg:#2b2d30 bg:#57c7fe"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
#[directory.substitutions]

[git_branch]
symbol = ""
truncation_length = 24
style = "fg:#2b2d30 bg:#f3f99c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fsg:#2b2d30 bg:#f3f99c"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = "⬡"
style = "fg:#2b2d30 bg:#00ffa5"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "🦀"
style = "fg:#2b2d30 bg:#00ffa5"
format = '[ $symbol ($version) ]($style)'


