format = """
[](bg:#9A348E fg:#9A348E)\
$username\
$hostname\
$sudo\
[](bg:#DA637D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#86BBD8)\
$nodejs\
$rust\
[](fg:#86BBD8 bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[hostname]
trim_at = ""
style = "bg:#9A348E"
format = '[(@$hostname)]($style)'

[sudo]
disabled = false
style = "bg:#9A348E"
format = '[$symbol]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
#[directory.substitutions]

[git_branch]
symbol = ""
truncation_length = 24
style = "bg:#FCA17D"
format = '[[ $symbol $branch ](bg:#FCA17D)]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[[($all_status$ahead_behind )](bg:#FCA17D)]($style)'

[nodejs]
symbol = "⬢"
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[rust]
symbol = "🦀"
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

# TODO: nice bg dark blue: #33658A
